### ISSUE TITLE
Acknowledged contact alerts should be cleared

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-ios#114]
After hitting 'acknowledge', the contact alert page shouldn't re-show the same alerts over and over again.

**Comment by scottleibrand** [comment]
May be fixed by the same change as https://github.com/Co-Epi/app-ios/issues/115

**Comment by i-schuetz** [comment]
If matched only new keys (delta from last fetch), this problem would be solved, but we'd miss possible new CENs for old keys. Not sure whether there's a solution for this or perhaps it's admissible, given that users that report symptoms are likely to take protective measures / distance.

The other solution would be doing the filtering after the matches. When the alerts are ACK-ed we'd only set a "deleted" flag on them (instead of deleting), and if we get the same matches they'd not overwrite these entries, so they'd stay deleted. There would be a regular job deleting too old alerts (more than 3 or 4 weeks), which we need also to delete old CENs.

**Comment by scottleibrand** [comment]
New TCNs for old keys should be disallowed: the `rak` needs to be rotated whenever we submit a report, so that no one receiving the report can impersonate the reporter by generating new TCNs with the newly-revealed `rvk` and `tck`s.

**Comment by i-schuetz** [comment]
I fixed it for 0.2 by marking the reports as deleted (as described). Can you open a new issue for this?

**Comment by i-schuetz** [comment]
For 0.2 I'm marking the alerts as deleted (as described). Can you open a new issue for the 0.4 backend?

**Comment by ivnsch** [comment]
Alerts stay cleared now.
