### ISSUE TITLE
Clarification of branch to use and build instructions for new users

### ISSUE THREAD

**Issue by mikew67** [Co-Epi/app-ios#98]
**Problem:** With turbulent changes in this rep, it's unclear for new users/testers how to build the app and which branch to use.

**Solution*** Add two entries to the README for this repo:
 * A pointer to "Getting Started" a build instructions doc (and might as well add testing instructions, too). (Mark Ingle has written a build doc for iOS already).
 * A (dynamically changing?) note in the README abut which repo branch to build from.

**Comment by i-schuetz** [comment]
I added setup instructions to the README. For the branches, we use [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), but I'm a bit wary of linking to it in the README, because we're not following it strictly at the moment. In short, `develop` contains our most recent (merged) work, and `master` the releases.
